name: apollo

channels:
    - conda-forge
    - anaconda

dependencies:
    # Core stack
    - python>=3.6
    - numpy
    - scipy
    - matplotlib
    - cartopy
    - pandas
    - dask
    - dask-ml
    - xarray>=0.10
    - netcdf4
    - pynio
    - scikit-learn
    - xgboost
    - requests

    # web app
    - flask
    - waitress

    # Documentation
    - sphinx
    - sphinx_rtd_theme

    # Dev tooling
    - ipython
